#ifndef R_GAME
#define R_GAME

typedef struct {
	int RANDOM_NUMBER;
	int DISPLAY_NUMBER_1;
	int DISPLAY_NUMBER_2;
    int P1_RESULT;
    int P2_RESULT;
    int WINNER;// -1 eeror ,0 draw ,1 p1 win ,2 p2win
    unsigned long tick100us;//0.0001s //-
    int PLAYER1_STATE; //-
    int PLAYER2_STATE;//-
} REACTION_OUTPUT_TABLE;

REACTION_OUTPUT_TABLE REACTION_START(REACTION_OUTPUT_TABLE REACTO_TABLE); 
REACTION_OUTPUT_TABLE REACTION_UPDATE(REACTION_OUTPUT_TABLE REACTO_TABLE);
REACTION_OUTPUT_TABLE REACTION_UPDATE_WHO_WIN(REACTION_OUTPUT_TABLE REACTO_TABLE);

#endif